spring:
  messages:
    basename: messages, errors #오류 메세지 errors.properties 등록, messages는 default값

  servlet:
    multipart:
      max-file-size: 10MB # 파일 하나 당 크기
      max-request-size: 50MB #한 요청에 Multipart 전체 크기 제한

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false #영속성 컨텍스트를 트랜잭션 종료시 종료

# 세션 타임아웃 설정
server:
  servlet:
    session:
      timeout: 600

logging.level:
  org.hibernate.SQL: DEBUG
  org.springframework.web: INFO